apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
    - name: tasks
      port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
