import os, runClient, sys
print("##########################################################")
print("#                                                        #")
print("#             OCI - Global HPC Team                      #")
print("#      Financial Services Monte Carlo Simulator          #")
print("#                 Version 1.0                            #")
print("#                                                        #")
print("##########################################################")
print("RabbitMQHost = " + os.environ['RABBITMQ_HOST'])
print("RabbitMQQueue = " + os.environ['RABBITMQ_TASKQUEUE'])
print("RabbitMQQueueSplittable = " + os.environ['RABBITMQ_TASKQUEUE_SPLITTABLE'])
print("SplunkHost = " + os.environ['SPLUNK_HOST'])
print("SplunkIndex = " + os.environ['SPLUNK_INDEX'])
print("SplunkSourceType = " + os.environ['SPLUNK_SOURCETYPE'])
#print("MinSimulations = " + os.environ['MIN_SIMULATIONS'])
print("NumSteps = " + os.environ['NUM_STEPS'])
print("Reporting = " + os.environ['REPORTING'])
runClient.client(sys.argv[1])
