apiVersion: v1
kind: ReplicationController
metadata:
  name: kubernetes-api-controller
  labels:
    component: kubernetes-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-api
        component: kubernetes-api
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/kubernetes-api:1.0.0
          name: kubernetes-api-container
          env:
          - name: SPLUNK_HOST
            value: splunk-service
          - name: SPLUNK_USER
            value: admin
          - name: SPLUNK_PASSWORD
            value: password
          - name: SPLUNK_INDEX
            value: main
          - name: SPLUNK_SOURCETYPE
            value: _json
          - name: REPORTING_FREQUENCY
            value: "300"
      nodeSelector:
        name: HPC
