apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: mcs
  ports:
    - name: rabbitmqweb
      port: 15672
      targetPort: 15672
    - name: rabbitmqtasks
      port: 5672
      targetPort: 5672
    - name: splunkweb
      port: 8000
      targetPort: 8000
    - name: splunkindex
      port: 8089
      targetPort: 8089
  type: LoadBalancer
