apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: taskQueue
  ports:
    - name: gui
      port: 15672
      targetPort: 15672
    - name: tasks
      port: 5672
      targetPort: 5672
  type: LoadBalancer
