apiVersion: v1
kind: ReplicationController
metadata:
  name: mcv-controller
  labels:
    component: mcv
spec:
  replicas: 216
  template:
    metadata:
      labels:
        app: mcv
        component: mcv
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/mcv:2.2.2
          name: mcv-container
          env:
          - name: RABBITMQ_HOST
            value: rabbitmq-service
          - name: RABBITMQ_TASKQUEUE
            value: tasks_in
          - name: MIN_SIMULATIONS
            value: "3000000"
          - name: RABBITMQ_PREFETCHCOUNT
            value: "5"
      nodeSelector:
        name: HPC
