apiVersion: v1
kind: ReplicationController
metadata:
  name: mcv-parent-controller
  labels:
    component: mcv-parent
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: mcv
        component: mcv
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/mcv-parent:1.0.6
          name: mcv-parent-container
          env:
          - name: RABBITMQ_HOST
            value: rabbitmq-service
          - name: RABBITMQ_TASKQUEUE
            value: tasks_in
          - name: RABBITMQ_TASKQUEUE_SPLITTABLE
            value: tasks_in_splittable
          - name: MIN_SIMULATIONS
            value: "3000000"
          - name: RABBITMQ_PREFETCHCOUNT
            value: "5"
      nodeSelector:
        name: HPC
