apiVersion: v1
kind: PersistentVolume
metadata:
 name: splunk-fsspv
spec:
 storageClassName: splunk-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
# Replace this with the IP of your FSS file system in OCI
   server: 10.0.10.88
#   # Replace this with the Path of your FSS file system in OCI
   path: "/FileSystem-20211110-1807-30"
   readOnly: false
