apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: splunk-fsspvc-new
spec:
 storageClassName: splunk-fss-new
 accessModes:
 - ReadWriteMany
 resources:
  requests:
 # Although storage is provided here it is not used for FSS file systems
    storage: 100Gi
 volumeName: splunk-fsspv-new
