apiVersion: v1
kind: Service
metadata:
  labels:
    component: splunk
  name: splunk-service
spec:
  ports:
    - name: gui
      port: 8000
    - name: server
      port: 8089
  selector:
    app: taskQueue
    component: splunk
