apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: splunk
  name: splunk-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: splunk
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/splunk:latest
          name: splunk
          env:
          - name: SPLUNK_PASSWORD
            value: password
          - name: SPLUNK_START_ARGS
            value: --accept-license
          ports:
            - containerPort: 8000
            - containerPort: 8089
          resources:
            limits:
              cpu: 1000m
      nodeSelector:
        name: HPC
