apiVersion: v1
kind: ReplicationController
metadata:
  name: intel-worker-controller
  labels:
    component: mcs
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: mcs
        component: mcs
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/intel-worker:latest
          name: intel-worker-container
          env:
          - name: RABBITMQ_HOST
            value: rabbitmq-service
          - name: RABBITMQ_TASKQUEUE
            value: tasks_in
          - name: NUM_STEPS
            value: "10"
          - name: RABBITMQ_PREFETCHCOUNT
            value: "5"
      nodeSelector:
        kubernetes.io/arch: amd64
