apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mcs
        component: mcs
    spec:
      containers:
        - image: iad.ocir.io/hpc_limited_availability/rabbitmq:latest
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 2000m
      nodeSelector:
        kubernetes.io/arch: amd64
