kind: StorageClass
#apiVersion: storage.k8s.io/v1beta1
apiVersion: storage.k8s.io/v1
metadata:
  name: splunk-fss
provisioner: oracle.com/splunk-fss
parameters:
  # Insert mount target from the FSS here
  mntTargetId: ocid1.mounttarget.oc1.iad.aaaaaa4np2tch5mynfqwillqojxwiotjmfsc2ylefuzqaaaa
